version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
      args:
        - USERNAME=${USERNAME}
        - USER_UID=${USER_UID}
    container_name: 'webserver'
    depends_on:
      - mysql
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
      - ${SOLR_DIR-./data/solr}:/home/${USERNAME}/server/solr
    restart: always
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    ports:
      - "127.0.0.1:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'phpmyadmin'
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    depends_on:
      - mysql
      - webserver
    volumes: 
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
  solr:
    image: solr:latest
    container_name: 'solr'
    restart: always
    ports:
      - "8983:8983"
    volumes: 
        - ${SOLR_DIR-./data/solr}:/home/${USERNAME}/server/solr
    command:
      - solr-precreate
      - gettingstarted
    environment:
      SOLR_HOME: /home/${USERNAME}/server/solr
  memcached:
    image: memcached
    container_name: 'memcached'
    restart: always