# docker-sync for Mac and Windows docker performance https://docker-sync.readthedocs.io/

version: '3'

services:
  webserver:
    volumes:
      - web-sync:/var/www/html:cached

volumes:
  web-sync:
    external: true