#!/bin/bash
webserverDir="$(dirname "$(dirname $(readlink -f $0))")"
docker run -i --rm -v $(pwd):$(pwd) -v $webserverDir/data/phpcs:/data -v $webserverDir/data/phpcs/CodeSniffer.conf:/usr/bin/CodeSniffer.conf cytopia/phpcs $*
